### PR TITLE
Always run HTTP request code on Context.

### PR DESCRIPTION
**Pull request by zhiguangwang**
AWS SDK would call execute() on internal thread pool for retry attempts.

This issue is similar to #2.

### CODE REVIEW

**Comment by aesteve** [comment]
Hello, and thanks a lot for your contribution.

I'm sorry I changed a lot of things today regarding this repository in order to hand it over [reactiverse organization](https://github.com/reactiverse).

Would it be possible for you to rebase with the master branch (just a very small conflict with the `Logger` I guess).

Also, would it be possible to add a test that shows the "retry" issue you faced ? I did not face it myself and even though I'm trusting you 100% it'd be great to have a unit test for catching possible future regressions. I don't even think you need localstack, just a unit test where you target a mock http server that returns a retriable error code the first time it's accessed, then 200.

Thanks.

**Comment by aesteve** [comment]
Just to let you know : I'm close top having a test work, and I faced your issue in the test:

capture d ecran 2019-01-13 a 11 11 26

```
11:10:56.586 [vert.x-eventloop-thread-4] DEBUG software.amazon.awssdk.request - Received error response: 500
11:10:56.607 [vert.x-eventloop-thread-5] DEBUG software.amazon.awssdk.request - Retryable error detected, will retry in 65ms, attempt number -1
11:10:56.679 [sdk-ScheduledExecutor-0-0] DEBUG software.amazon.awssdk.request - Retrying Request: DefaultSdkHttpFullRequest(httpMethod=GET, protocol=http, host=localhost, port=9876, encodedPath=/2015-03-31/functions/dummy, headers=[amz-sdk-invocation-id, Content-Type, User-Agent], queryParameters=[])
``` 

The retry code is using `sdk-ScheduledExecutor-0-0` instead of `vertx-event-loop-thread`.
As soon as I have a proper test working (the assertion on context is not that easy, because the callback, even if retried, is executed in the correct context, but not the retry itself).

**Comment by aesteve** [comment]
I've added a test attempt to your branch. This is not perfect, but I can confirm such a test is failing on master, but not on your branch.

@zhiguangwang please review. If we agree, let's merge it.

**Comment by zhiguangwang** [comment]
@aesteve The test code are good enough for me.

Thanks for following up so quickly!

**Pull request merged**
